orders/urls.py
from django.urls import  path

from .views import *


urlpatterns = [
    # path("station/", order_station, name="order-station"),
    path("station/", StationListView.as_view(), name="order-station"),
    path("oil/<int:station_id>", order_oil, name="order-oil"),
    path('pay/<str:order_id>', pay, name='pay'),
    path('paid/<str:order_id>/<int:reference_id>', paid, name='paid'),
    path("seller/orders/", seller_orders, name="seller-orders"),
    path("seller/<str:order_id>", seller_order_detail, name="seller-order-detail"),
    path("delivered/<str:order_id>", delivered, name="delivered"),
    path("received/<str:order_id>", received, name="received"),
    
    
    path("customer/orders/", customer_orders, name="customer-orders"),
    path("customer/<str:order_id>", customer_order_detail, name="customer-order-detail"),
]

premix/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static
def home(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')


def join(request):
    return render(request, 'join.html')


urlpatterns = [
    path('admin/', admin.site.urls, name="admin-panel"),
    re_path(r'^$', home, name='home'),
    path('contact/', contact, name='contact'),
    path('join/', join, name='join'),
    path('users/', include("users.urls")),
    path('station/', include("stations.urls")),
    path('orders/', include("orders.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from .views import *


urlpatterns = [
    path("login", login_buyer, name="login-custom"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/dashboard', open_dashboard, name="admin-dashboard"),
    path('admin/register-customer', register_customer, name="register-customer"),
    path('admin/register-seller', register_seller, name="register-seller"),
    path('customer-detail/<int:customer_id>', customer_detail, name="customer-detail"),
    path('update-customer/<int:customer_id>', update_customer, name="update-customer"),
]

orders/models.py
from email.policy import default
from django.db import models

# Create your models here.
class Orders(models.Model):
    order_id = models.CharField(max_length=50, unique=True)
    quantity = models.CharField(max_length=10)
    price = models.FloatField(max_length=10)
    received = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    ordered_time = models.DateTimeField(auto_now_add=True)
    delivered_time = models.DateTimeField(null=True, blank=True)
    received_time = models.DateTimeField(null=True, blank=True)
    station = models.ForeignKey('stations.Station', on_delete=models.CASCADE)
    customer = models.ForeignKey('users.Customer', on_delete=models.CASCADE)
    delivery = models.BooleanField(default=False)
    
class Price(models.Model):
    price = models.CharField(max_length=10)
    time_created = models.DateTimeField(auto_now=True, auto_now_add=False)

orders/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Orders


class OrderForm(forms.ModelForm):
    price = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control', 'readonly':'True'}))
    quantity = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control','placeholder': 'in gallons'}))

    class Meta:
        model = Orders
        fields = ( 'quantity', 'price')

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm, UserCreationForm
from django import forms

from users.models import Customer


class RegisterBuyerForm(forms.ModelForm):
    email = forms.EmailField(widget= forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(max_length=12, widget= forms.TextInput(attrs={'class': 'form-control'}))
    profile_picture = forms.ImageField(required=True)
    #the widget changes the default styling to to a bootstrap default form stylings
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'phone', "profile_picture")

class RegisterSellerForm(forms.ModelForm):
    username= forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget= forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    profile_picture = forms.ImageField(required=True)
    name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    # quantity = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    geolocation_longitude = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    geolocation_latitude = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))

    #the widget changes the default styling to to a bootstrap default form stylings
    class Meta:
        model = User
        fields = ('username', 'first_name',
                  'last_name', 'email', 'phone',
                  "profile_picture", "name", 
                  'address', 'phone',
                  "geolocation_longitude", "geolocation_latitude",
                  )


class EditUserForms(forms.ModelForm):
    username = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget= forms.EmailInput(attrs={'class': 'form-control'}))

#the widget changes the default styling to to a bootstrap default form stylings
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

class PictureForms(forms.ModelForm):
    profile_picture = forms.ImageField(required=True)
    phone = forms.CharField(max_length=12, widget= forms.TextInput(attrs={'class': 'form-control'}))


#the widget changes the default styling to to a bootstrap default form stylings
    class Meta:
        model = Customer
        fields = ('profile_picture', 'phone')


class PasswordChangeForms(PasswordChangeForm):
    old_password = forms.CharField(widget= forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(widget= forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(widget= forms.PasswordInput(attrs={'class': 'form-control'}))

    
#the widget changes the default styling to to a bootstrap default form stylings
    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

orders/views.py
from datetime import datetime
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import messages
from orders.forms import OrderForm
from stations.models import Station
from .models import Orders, Price
from pypaystack import Transaction, Customer, Plan
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

#get all orders
def get_orders(request):
    orders = Orders.objects.all()
    return render(request, 'orders/orders.html', {'orders': orders})

# get an order
def get_order_detail(request, id):
    order = Orders.objects.get(id=id)
    return render(request, 'orders/order_detail.html', {'order': order})



# search order through JSON

def search_order(request):
    data = []
    if request.method == 'POST':
        search_text = request.POST['search_text']
        if search_text is not None:
            orders = Orders.objects.filter(order_id__icontains=search_text)
            for order in orders:
                order_data = {
                    "id" : order.id,
                    "order_id": order.order_id,
                    "order_date": order.order_date,
                    "order_status": order.order_status,
                    "order_total": order.order_total,
                }
                data.append(order_data)
            
    return JsonResponse({'data': data}, safe=False)



# user orders
def customer_orders(request):
    orders = Orders.objects.filter(customer=request.user.customer, paid=True).order_by("-ordered_time")
    price = Price.objects.all().order_by("-time_created").first()
    return render(request, 'customer/customer_orders.html', {'orders': orders, 'price': price})

def customer_order_detail(request, order_id):
    order = Orders.objects.get(order_id=order_id)
    price = Price.objects.all().order_by("-time_created").first()

    return render(request, 'customer/customer_order_detail.html', {'order': order, 'price': price})


# seller orders
def seller_orders(request):
    unprocessed_orders = Orders.objects.filter(station=request.user.seller.station, delivered=False, received=False, paid=True).order_by("-ordered_time")
    processed_orders = Orders.objects.filter(station=request.user.seller.station, delivered=True, received=True, paid=True).order_by("-ordered_time")
    
    station = Station.objects.get(id=request.user.seller.station.id)
    oil_quantity = station.quantity
    return render(request, 'seller/orders.html', {'unprocessed_orders': unprocessed_orders, 'processed_orders': processed_orders, 'oil_quantity': oil_quantity})


def seller_order_detail(request, order_id):
    order = Orders.objects.get(order_id=order_id)
    return render(request, 'seller/order_detail.html', {'order': order})





def order_oil(request, station_id):    
    order_form = OrderForm()
    price = Price.objects.all().order_by("-time_created").first()
    station = Station.objects.get(id=station_id)
    full_name = request.user.first_name + " " + request.user.last_name
    get_initials(fullname=full_name)
    order_id = get_initials(fullname=full_name) +"-"+ generate_random_numbers()
    if request.method == 'POST':
        if order_form.is_valid:
            delivery_box = request.POST.get("box")
            if delivery_box:
                delivery = True
            else:
                delivery = False
            order = Orders.objects.create(
                order_id = order_id,
                customer = request.user.customer,
                station = station,
                quantity = request.POST['quantity'],
                price = request.POST['price'], 
                delivery = delivery           
            )
           
        return redirect('pay', order_id=order.order_id)
    else:
        return render(request, 'customer/buy.html', 
                      {'order_form': order_form, 'order_id': order_id, 'price': price, 'station': station})
        
        
        

def get_initials(fullname):
  xs = (fullname)
  name_list = xs.split()

  initials = ""

  for name in name_list:  # go through each name
    initials += name[0].upper()  # append the initial

  return initials

def generate_random_numbers():
        return User.objects.make_random_password(length=6, allowed_chars='123456789')




def pay(request, order_id):
    order = Orders.objects.get(order_id=order_id)
    price = Price.objects.all().order_by("-time_created").first()

    return render(request, 'customer/pay.html', {'order': order, 'price': price})

def paid(request, order_id, reference_id):
    order = Orders.objects.get(order_id=order_id)
    station = Station.objects.get(id=order.station.id)
    transaction = Transaction(authorization_key="sk_test_38b5f48935d447f62045a3a37654d63040fdc70d")
    response  = transaction.verify(reference_id)
    if response[3].get('status') == "success":
        station.quantity = int(station.quantity) - int(order.quantity)
        station.save()
        order.paid = True
        order.save()
        messages.success(request, response[2], extra_tags='alert alert-success alert-dismissible fade show')
        return HttpResponseRedirect(reverse('customer-order-detail', kwargs={'order_id': order.order_id,}))
    else:
        messages.success(request, response[2], extra_tags='alert alert-success alert-dismissible fade show')
        return HttpResponseRedirect(reverse('pay', kwargs={'id': order_id,}))
    # return redirect("order-station")

def received(request, order_id):
    order = Orders.objects.get(order_id=order_id)
    order.received = True
    order.received_time = datetime.now()
    order.save()
    return redirect('customer-orders')

def delivered(request, order_id):
    order = Orders.objects.get(order_id=order_id)
    order.delivered = True
    order.delivered_time = datetime.now()
    order.save()
    return redirect('seller-orders')


def order_station(request):
    stations = Station.objects.all()
    price = Price.objects.all().order_by("-time_created").first()

    return render(request, 'customer/order_station.html', {'stations': stations, 'price': price})

from django.views.generic import  ListView

class StationListView(ListView):
    model = Station
    template_name = 'customer/order_station.html'
    context_object_name = "stations"
    paginate_by = 20
    
    def get_queryset(self):
        query = self.request.GET.get('search')
        if query:
            object_list = self.model.objects.filter(name__contains=query)
        else:
            object_list = self.model.objects.all()
        return object_list
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["price"] = Price.objects.all().order_by("-time_created").first()
        return context



# def get_orders(request):
#     orders = Orders.objects.all()
#     return render(request, 'admin/all_order.html', {"order":orders})

templates/seller/order_detail.html
{% extends "header.html" %}

{% block content %}
<h2>Seller Orders {{order.order_id}}</h2>

  <div class="container col-lg-6 mb-3 mt-5">
    <div class=" text-center p-3" style="box-shadow: rgba(17, 12, 46, 0.15) 0px 48px 100px 0px;">
      <h6 class="mt-5">Order Detail</h6>
      <div class="card  mb-5">
        <table class="table table-sm align-middle mb-0 bg-white">
          <tbody>
            <tr>
              <td>
                <p class="text-muted mb-0">Order ID</p>
              </td>
              <td>
                <p class="fw-normal mb-1">{{order.order_id}}</p>
              </td>
            </tr>
            <tr>
              <td>
                <p class="text-muted mb-0">quantity</p>
              </td>
              <td>
                <p class="fw-normal mb-1">{{order.quantity}}</p>
              </td>
            </tr>
            <tr>
              <td>
                <p class="text-muted mb-0">Amount</p>
              </td>
              <td>
                <p class="fw-normal mb-1">{{order.price}}</p>
              </td>
            </tr>
            <tr>
              <td>
                <p class="text-muted mb-0">Delivered</p>
              </td>
              <td>
                <p class="fw-normal mb-1">{{order.delivered}}</p>
              </td>
            </tr>
            <tr>
              <td>
                <p class="text-muted mb-0">Order Time</p>
              </td>
              <td>
                <p class="fw-normal mb-1">{{order.ordered_time}}</p>
              </td>
            </tr>
            <tr>
              <td>
                <p class="text-muted mb-0">Delivery</p>
              </td>
              <td>
                {% if order.delivery %}
                <p class="fw-normal mb-1">Yes</p>
                {% else %}
                <p class="fw-normal mb-1">No</p>
                {% endif %}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <h6>Buyer Detail</h6>
      <div class="card mb-3" style="max-width: 800px; ">
        <div class="row">
          <div class="col-4">
            <img src="{{order.customer.profile_picture.url}}" alt="Username"
              class="rounded-start" height="200" width="200"/>
          </div>
          <div class="col-8">
            <div class="card-body text-start">
              <h5 class="card-title">Username : {{order.customer.user.username}}</h5>
              <h6 class="card-title">Customer Name: {{order.customer.user.first_name}} {{order.customer.user.last_name}}</h6>
              <h6 class="card-title">Customer Email: {{order.customer.user.email}} </h6>
              <p class="card-text">
                Phone: {{order.customer.phone}}
              </p>
              <p class="card-text">
                <small class="text-muted"></small>
              </p>
            </div>
          </div>
        </div>
      </div>

      <!-- Button trigger modal -->
      {% if not order.delivered %}        
      <button type="button" class="btn btn-dark btn-block m-4 col-7 rounded-pill" data-bs-toggle="modal"
        data-bs-target="#exampleModal">
        Delivered?
      </button>
      {% endif %}
    </div>


  </div>


  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delivered Fuel</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">Are you sure?</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-mdb-dismiss="modal">No</button>
          <a href="{% url 'delivered' order.order_id %}" class="btn btn-success">Yes</a>
        </div>
      </div>
    </div>
     
    {% endblock content %}

templates/seller/orders.html
{% extends "header.html" %}



{% block content %}

<h2>Operator Orders</h2>
<h2>Fuel quantity : {{oil_quantity}} Gallons</h2>
<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button"
      role="tab" aria-controls="pills-home" aria-selected="true">Unprocessed</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button"
      role="tab" aria-controls="pills-profile" aria-selected="false">Processed</button>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <!-- UNProcessed -->
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">

    <div class="container col-lg-6 ">
      <!-- card body starts here -->
      {% for order in unprocessed_orders %}

      <div class=" text-center" style="box-shadow: rgba(17, 12, 46, 0.15) 0px 48px 100px 0px;">
        <div class="card ">
          <table class="table table-sm align-middle mb-0 bg-white">
            <tbody>
              <tr>
                <td>
                  <p class="text-muted mb-0">Order ID</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.order_id}}</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p class="text-muted mb-0">quantity</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.quantity}}</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p class="text-muted mb-0">Amount</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.price}}</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p class="text-muted mb-0">Delivered</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.delivered}}</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p class="text-muted mb-0">Received</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.received}}</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p class="text-muted mb-0">Order Time</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.ordered_time}}</p>
                </td>
              </tr>

            </tbody>
          </table>
          <a href="{% url 'seller-order-detail' order.order_id %}" class="stretched-link"></a>
        </div>

      </div>
      {% endfor %}
      <!-- end here -->
    </div>
  </div>
  <!-- UNProcessed -->

  <!-- Processed -->
  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
    
    <div class="container col-lg-6 ">
      <!-- card body starts here -->
      {% for order in processed_orders %}

      <div class=" text-center" style="box-shadow: rgba(17, 12, 46, 0.15) 0px 48px 100px 0px;">
        <div class="card ">
          <table class="table table-sm align-middle mb-0 bg-white">
            <tbody>
              <tr>
                <td>
                  <p class="text-muted mb-0">Order ID</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.order_id}}</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p class="text-muted mb-0">quantity</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.quantity}}</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p class="text-muted mb-0">Amount</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.price}}</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p class="text-muted mb-0">Delivered</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.delivered}}</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p class="text-muted mb-0">Received</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.received}}</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p class="text-muted mb-0">Order Time</p>
                </td>
                <td>
                  <p class="fw-normal mb-1">{{order.ordered_time}}</p>
                </td>
              </tr>

            </tbody>
          </table>
          <a href="{% url 'seller-order-detail' order.order_id %}" class="stretched-link"></a>
        </div>

      </div>
      {% endfor %}
      <!-- end here -->
    </div>
  </div>
</div>

<div class="container col-lg-6">
  <div class="input-group">
    <!-- <input type="search" id="search-input" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" /> -->
    <!-- <button type="button" id="search-button" class="btn btn-outline-primary">search</button> -->
  </div>
</div>
<style>
  .nav-link{
    background-color: #fff;
    color: black;
  }
  
  .active.nav-link{
    background-color: rgb(0, 0, 0) !important;
    color: rgb(255, 255, 255) !important;
  }
</style>
{% endblock content %}

<script type="text/javascript">
  const searchButton = document.getElementById('search-button');
  const searchInput = document.getElementById('search-input');
  searchButton.addEventListener('click', () => {
    const inputValue = searchInput.value;
    alert(inputValue);
  });
</script>

templates/seller/register_seller.html
{% extends "header.html" %}

{% block style %}

{% endblock style %}

{% block title %}
Register Buyer
{% endblock title %}


{% block content %}
<div class="container col-lg-8 mb-3 mt-5">
  <div class=" text-center p-3" style="
  border-radius: 10px;
  background: #fffefe;
  box-shadow: 15px 15px 30px #bebebe,
              -15px -15px 30px #ffffff;">

    <form method="Post" enctype="multipart/form-data">
      {% csrf_token %}
      <div id="Div1">
        <h2>Operator Details</h2>

        <div class="row mb-4">
          <div class="col">
            <div class="form-outline">
              {{form.username}}
              <label class="form-label" for="id_username">Username</label>
            </div>
          </div>
          <div class="col">
            <div class="form-outline">
              {{form.email}}
              <label class="form-label" for="id_email">Email</label>
            </div>
          </div>
        </div>
        <div class="row mb-4">
          <div class="col">
            <div class="form-outline">
              {{form.first_name}}
              <label class="form-label" for="id_first_name">First name</label>
            </div>
          </div>
          <div class="col">
            <div class="form-outline">
              {{form.last_name}}
              <label class="form-label" for="id_last_name">Last name</label>
            </div>
          </div>
        </div>
        <div class="row mb-4">
          <div class="col">
            <div class="form-outline">
              {{form.profile_picture}}
              <label class="form-label" for="customFile">Passport Picture</label>
            </div>
          </div>
          <div class="col">
            <div class="form-outline">
              <img id="blah"
                src="https://images.vexels.com/media/users/3/129616/isolated/preview/fb517f8913bd99cd48ef00facb4a67c0-businessman-avatar-silhouette-by-vexels.png"
                class="img-fluid " width="200" height="200" />
            </div>
          </div>
        </div>

        <div class="text-end">
          <a href="#" class="btn btn-dark rounded-pill align-content-end text-end" onclick="divVisibility('Div2');"><i
              class="bi bi-arrow-right-square-fill"></i> Next</a>
        </div>
      </div>
      <div id="Div2" style="display: none;">
        <h2>Station Details</h2>
        <div class="form-outline">
          {{form.name}}
          <label class="form-label" for="id_name">Station Name</label>
        </div>
        <div class="row mb-4">
          <div class="col">
            <div class="form-outline">
              {{form.address}}
              <label class="form-label" for="id_address">Address</label>
            </div>
          </div>
          <div class="col">
            <div class="form-outline">
              {{form.phone}}
              <label class="form-label" for="id_phone">Phone</label>
            </div>
          </div>
        </div>
        <div class="row mb-4">
          <p>Station Geolocation</p>
          <div class="col">
            <div class="form-outline">
              {{form.geolocation_longitude}}
              <label class="form-label" for="id_geolocation_longitude">Longitude</label>
            </div>
          </div>
          <div class="col">
            <div class="form-outline">
              {{form.geolocation_latitude}}
              <label class="form-label" for="id_geolocation_latitude">Latitude</label>
            </div>
          </div>
        </div>
        <div class="row mt-4 mb-4">
          <div class="col">
            <!-- <a href="#" class="align-items-start" onclick="divVisibility('Div1');">Div1</a> -->
            <div class="text-start">
              <a href="#" class="btn btn-dark rounded-pill align-content-end text-end"
                onclick="divVisibility('Div1');"><i class="bi bi-arrow-left-square-fill"></i> Prev</a>
            </div>
          </div>
          <div class="col ">
            <div class="text-end">
              <button type="submit" 
                class=" btn btn-dark btn-block rounded-pill">Register</button>
            </div>
          </div>
        </div>
      </div>

      <!-- Submit button -->


    </form>


  </div>
</div>


{% endblock content %}

{% block script %}
<script>
  document.getElementById("id_profile_picture").classList.add("form-control")
</script>
<script>

  id_profile_picture.onchange = evt => {
    const [file] = id_profile_picture.files
    if (file) {
      blah.style.display = ""
      blah.src = URL.createObjectURL(file)
    }
  }
</script>
<script>
  var divs = ["Div1", "Div2",];
  var visibleDivId = null;
  function divVisibility(divId) {
    if (visibleDivId === divId) {
      visibleDivId = null;
    } else {
      visibleDivId = divId;
    }
    hideNonVisibleDivs();
  }
  function hideNonVisibleDivs() {
    var i, divId, div;
    for (i = 0; i < divs.length; i++) {
      divId = divs[i];
      div = document.getElementById(divId);
      if (visibleDivId === divId) {
        div.style.display = "block";
      } else {
        div.style.display = "none";
      }
    }
  }
</script>

{% endblock script %}